/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 35
#define YY_END_OF_BUFFER 36
static yyconst short int yy_accept[335] =
    {   0,
        0,    0,   36,   34,   33,   32,   34,   34,   34,   26,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,    0,   29,    0,    0,    0,
       26,    0,   30,   30,    0,    0,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       23,   30,   30,   30,   30,   21,   28,   27,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   24,   30,   30,   11,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,    3,   30,    4,   30,   19,   30,   30,    5,

       30,   30,   30,   30,   17,   30,   30,    6,   30,   30,
       20,   30,   30,   30,   12,   30,   30,   30,   30,   30,
       30,   30,   30,    9,   30,    1,   30,   30,    7,   13,
       15,   16,   30,   14,   30,   30,   18,   25,   10,   30,
       30,   22,   30,   30,    2,    8,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,

       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,

       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   31,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    5,    1,
        1,    1,    6,    1,    6,    7,    1,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    1,    1,    1,
        1,    1,    1,    1,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,   10,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        1,   11,    1,    1,   12,    1,   13,   14,   15,   16,

       17,   18,   19,   20,   21,   22,    9,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,    9,    9,   33,
       34,    9,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[35] =
    {   0,
        1,    1,    1,    1,    2,    1,    1,    3,    4,    4,
        1,    3,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4
    } ;

static yyconst short int yy_base[538] =
    {   0,
        0,    0,  151, 1003, 1003, 1003,   31,  133,  131,   29,
       31,   36,    0,   37,   38,   59,   39,   45,   48,   51,
       72,   64,   69,   81,   46,   51, 1003,  126,  123,   89,
       67,  114,    0,   53,   91,  110,   79,   91,   92,   98,
      101,   99,  106,  115,  107,  122,  123,  124,  134,  137,
      142,  145,  150,  151,  152,  153, 1003,  112,    0,  159,
      160,  162,  168,  171,  176,  178,  179,  181,  190,  184,
      187,  198,  204,  205,  206,  207,  213,  214,  222,  223,
      225,    0,  224,  230,  231,  232,  239,  242,  249,  247,
      257,  259,  260,  262,  267,  268,  269,  274,  275,  277,

      284,  286,    0,  287,  289,  294,  292,  300,  302,  305,
      307,  308,  310,  316,  318,  323,  324,  332,  334,    0,
      331,  333,  339,  349,  351,  352,  354,  357,  359,  360,
      365,  367,  368,  375,    0,  378,  380,  381,  383,  386,
      388,  389,    0,  394,  396,  397,    0,  399,    0,  402,
        0,  404,    0,  405,    0,  407,    0,  412,    0,  413,
        0,  414,    0,  415,    0,  420,    0,  421,    0,  422,
        0,  423,    0,  428,    0,  429,    0,  430,    0,  431,
        0,  436,    0,  437,    0,  438,    0,  439,    0,  444,
        0,  445,    0,  446,    0,  447,    0,  452,    0,  453,

        0,  454,    0,  455,    0,  460,    0,  461,    0,  462,
        0,  463,    0,  468,    0,  469,    0,  470,    0,  471,
        0,  476,    0,  477,    0,  478,    0,  479,    0,  484,
        0,  485,    0,  486,    0,  487,    0,  492,    0,  493,
        0,  494,    0,  495,    0,  500,    0,  501,    0,  502,
        0,  503,    0,  508,    0,  509,    0,  510,    0,  511,
        0,  516,    0,  517,    0,  518,    0,  519,    0,  524,
        0,  525,    0,  526,    0,  527,    0,  532,    0,  533,
        0,  534,    0,  535,    0,  540,    0,  541,    0,  542,
        0,  543,    0,  548,    0,  549,    0,  550,    0,  551,

        0,  556,    0,  557,    0,  558,    0,  559,    0,  564,
        0,  565,    0,  566,    0,  567,    0,  572,    0,  573,
        0,  574,    0,  575,    0,  580,    0,  581,    0,  582,
     1003,    0,    0, 1003,  594,  598,  600,  602,  604,  606,
      608,  610,  612,  614,  616,  618,  620,  622,  624,  626,
      628,  630,  632,  634,  636,  638,  640,  642,  644,  646,
      648,  650,  652,  654,  656,  658,  660,  662,  664,  666,
      668,  670,  672,  674,  676,  678,  680,  682,  684,  686,
      688,  690,  692,  694,  696,  698,  700,  702,  704,  706,
      708,  710,  712,  714,  716,  718,  720,  722,  724,  726,

      728,  730,  732,  734,  736,  738,  740,  742,  744,  746,
      748,  750,  752,  754,  756,  758,  760,  762,  764,  766,
      768,  770,  772,  774,  776,  778,  780,  782,  784,  786,
      788,  790,  792,  794,  796,  798,  800,  802,  804,  806,
      808,  810,  812,  814,  816,  818,  820,  822,  824,  826,
      828,  830,  832,  834,  836,  838,  840,  842,  844,  846,
      848,  850,  852,  854,  856,  858,  860,  862,  864,  866,
      868,  870,  872,  874,  876,  878,  880,  882,  884,  886,
      888,  890,  892,  894,  896,  898,  900,  902,  904,  906,
      908,  910,  912,  914,  916,  918,  920,  922,  924,  926,

      928,  930,  932,  934,  936,  938,  940,  942,  944,  946,
      948,  950,  952,  954,  956,  958,  960,  962,  964,  966,
      968,  970,  972,  974,  976,  978,  980,  982,  984,  986,
      988,  990,  992,  994,  996,  998,   34
    } ;

static yyconst short int yy_def[538] =
    {   0,
      334,    1,  334,  334,  334,  334,  335,  336,  334,  334,
      337,  337,  338,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  335,  334,  335,  334,  336,
      334,  334,  339,  340,  335,  336,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  334,  334,  341,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  342,  342,  342,  342,  342,  342,
      342,  343,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,

      344,  344,  345,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  346,  346,  346,  347,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  349,  350,  350,  350,  350,  350,
      350,  350,  351,  352,  352,  352,  353,  354,  355,  356,
      357,  358,  359,  360,  361,  362,  363,  364,  365,  366,
      367,  368,  369,  370,  371,  372,  373,  374,  375,  376,
      377,  378,  379,  380,  381,  382,  383,  384,  385,  386,
      387,  388,  389,  390,  391,  392,  393,  394,  395,  396,
      397,  398,  399,  400,  401,  402,  403,  404,  405,  406,

      407,  408,  409,  410,  411,  412,  413,  414,  415,  416,
      417,  418,  419,  420,  421,  422,  423,  424,  425,  426,
      427,  428,  429,  430,  431,  432,  433,  434,  435,  436,
      437,  438,  439,  440,  441,  442,  443,  444,  445,  446,
      447,  448,  449,  450,  451,  452,  453,  454,  455,  456,
      457,  458,  459,  460,  461,  462,  463,  464,  465,  466,
      467,  468,  469,  470,  471,  472,  473,  474,  475,  476,
      477,  478,  479,  480,  481,  482,  483,  484,  485,  486,
      487,  488,  489,  490,  491,  492,  493,  494,  495,  496,
      497,  498,  499,  500,  501,  502,  503,  504,  505,  506,

      507,  508,  509,  510,  511,  512,  513,  514,  515,  516,
      517,  518,  519,  520,  521,  522,  523,  524,  525,  526,
      527,  528,  529,  530,  531,  532,  533,  534,  535,  536,
      334,  537,  537,    0,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,

      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,

      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334
    } ;

static yyconst short int yy_nxt[1038] =
    {   0,
        4,    5,    6,    7,    8,    9,    4,   10,   11,   12,
        4,   13,   14,   15,   16,   17,   18,   19,   11,   11,
       11,   11,   11,   11,   20,   21,   11,   22,   23,   24,
       11,   25,   11,   11,   27,   32,   31,  333,   33,   35,
       36,   28,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   43,   33,   33,   27,   33,   33,   33,   33,   33,
       59,   28,   33,   38,   59,   37,   33,   44,   47,   45,
       33,   33,   56,   32,   31,   33,   33,   46,   39,   33,
       33,   40,   48,   33,   41,   49,   59,   42,   33,   50,
       59,  334,   33,   29,   27,   52,   51,   54,   59,   59,

       53,   28,   59,   59,   63,   59,   59,   61,   59,   59,
       59,   55,   59,   59,   59,   68,   62,   59,   59,   58,
       30,   58,   59,   64,   65,   66,   59,   57,  334,   59,
       59,   59,   67,   59,   59,   59,   69,   71,   31,   73,
       70,   59,   72,   30,   59,   59,   74,   75,   59,   59,
      334,  334,   59,   59,   77,   76,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   78,   82,   82,  334,   82,
       82,   82,   84,   82,   79,   82,  334,  334,   82,   82,
       81,   80,   82,   82,   85,   82,   82,   82,   82,   82,
       82,   82,   82,   91,   82,   82,   86,   82,   82,   88,

       87,   82,   92,   90,  334,   82,  334,   94,   89,   82,
       93,   82,   82,   82,   82,   82,   82,   82,   82,   98,
       82,   82,  334,   99,   82,   82,   96,   97,   95,   82,
       82,  103,   82,   82,   82,  103,   82,  103,  103,  103,
      334,  103,  103,  103,  100,  102,  103,  106,  334,  103,
      103,  334,  101,  103,  103,  108,  103,  334,  103,  334,
      103,  107,  109,  105,  103,  110,  103,  103,  103,  103,
      103,  103,  113,  103,  103,  103,  103,  111,  103,  103,
      103,  103,  103,  115,  103,  103,  103,  112,  103,  117,
      116,  103,  114,  103,  120,  103,  120,  103,  120,  120,

      120,  120,  334,  120,  118,  120,  122,  120,  123,  120,
      119,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      334,  120,  127,  120,  126,  120,  334,  120,  334,  120,
      120,  120,  124,  334,  120,  120,  128,  125,  135,  120,
      135,  120,  135,  120,  135,  120,  135,  130,  334,  129,
      135,  131,  134,  334,  132,  133,  135,  137,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  138,
      135,  135,  135,  141,  135,  135,  135,  334,  135,  135,
      334,  139,  135,  140,  142,  143,  135,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  334,  143,

      143,  147,  145,  147,  147,  147,  149,  147,  147,  151,
      149,  153,  155,  151,  157,  153,  155,  146,  157,  159,
      161,  163,  165,  159,  161,  163,  165,  167,  169,  171,
      173,  167,  169,  171,  173,  175,  177,  179,  181,  175,
      177,  179,  181,  183,  185,  187,  189,  183,  185,  187,
      189,  191,  193,  195,  197,  191,  193,  195,  197,  199,
      201,  203,  205,  199,  201,  203,  205,  207,  209,  211,
      213,  207,  209,  211,  213,  215,  217,  219,  221,  215,
      217,  219,  221,  223,  225,  227,  229,  223,  225,  227,
      229,  231,  233,  235,  237,  231,  233,  235,  237,  239,

      241,  243,  245,  239,  241,  243,  245,  247,  249,  251,
      253,  247,  249,  251,  253,  255,  257,  259,  261,  255,
      257,  259,  261,  263,  265,  267,  269,  263,  265,  267,
      269,  271,  273,  275,  277,  271,  273,  275,  277,  279,
      281,  283,  285,  279,  281,  283,  285,  287,  289,  291,
      293,  287,  289,  291,  293,  295,  297,  299,  301,  295,
      297,  299,  301,  303,  305,  307,  309,  303,  305,  307,
      309,  311,  313,  315,  317,  311,  313,  315,  317,  319,
      321,  323,  325,  319,  321,  323,  325,  327,  329,  331,
      334,  327,  329,  331,   26,   26,   26,   26,   29,  334,

       29,   29,   34,   34,   33,   33,   59,   59,   60,   60,
       82,   82,   83,   83,  103,  103,  104,  104,  120,  120,
      121,  121,  135,  135,  136,  136,  143,  143,  144,  144,
      147,  147,  148,  148,  149,  149,  150,  150,  151,  151,
      152,  152,  153,  153,  154,  154,  155,  155,  156,  156,
      157,  157,  158,  158,  159,  159,  160,  160,  161,  161,
      162,  162,  163,  163,  164,  164,  165,  165,  166,  166,
      167,  167,  168,  168,  169,  169,  170,  170,  171,  171,
      172,  172,  173,  173,  174,  174,  175,  175,  176,  176,
      177,  177,  178,  178,  179,  179,  180,  180,  181,  181,

      182,  182,  183,  183,  184,  184,  185,  185,  186,  186,
      187,  187,  188,  188,  189,  189,  190,  190,  191,  191,
      192,  192,  193,  193,  194,  194,  195,  195,  196,  196,
      197,  197,  198,  198,  199,  199,  200,  200,  201,  201,
      202,  202,  203,  203,  204,  204,  205,  205,  206,  206,
      207,  207,  208,  208,  209,  209,  210,  210,  211,  211,
      212,  212,  213,  213,  214,  214,  215,  215,  216,  216,
      217,  217,  218,  218,  219,  219,  220,  220,  221,  221,
      222,  222,  223,  223,  224,  224,  225,  225,  226,  226,
      227,  227,  228,  228,  229,  229,  230,  230,  231,  231,

      232,  232,  233,  233,  234,  234,  235,  235,  236,  236,
      237,  237,  238,  238,  239,  239,  240,  240,  241,  241,
      242,  242,  243,  243,  244,  244,  245,  245,  246,  246,
      247,  247,  248,  248,  249,  249,  250,  250,  251,  251,
      252,  252,  253,  253,  254,  254,  255,  255,  256,  256,
      257,  257,  258,  258,  259,  259,  260,  260,  261,  261,
      262,  262,  263,  263,  264,  264,  265,  265,  266,  266,
      267,  267,  268,  268,  269,  269,  270,  270,  271,  271,
      272,  272,  273,  273,  274,  274,  275,  275,  276,  276,
      277,  277,  278,  278,  279,  279,  280,  280,  281,  281,

      282,  282,  283,  283,  284,  284,  285,  285,  286,  286,
      287,  287,  288,  288,  289,  289,  290,  290,  291,  291,
      292,  292,  293,  293,  294,  294,  295,  295,  296,  296,
      297,  297,  298,  298,  299,  299,  300,  300,  301,  301,
      302,  302,  303,  303,  304,  304,  305,  305,  306,  306,
      307,  307,  308,  308,  309,  309,  310,  310,  311,  311,
      312,  312,  313,  313,  314,  314,  315,  315,  316,  316,
      317,  317,  318,  318,  319,  319,  320,  320,  321,  321,
      322,  322,  323,  323,  324,  324,  325,  325,  326,  326,
      327,  327,  328,  328,  329,  329,  330,  330,  331,  331,

      332,  332,    3,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334
    } ;

static yyconst short int yy_chk[1038] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    7,   10,   10,  537,   11,   12,
       12,    7,   11,   12,   14,   15,   17,   12,   14,   15,
       17,   17,   18,   25,   26,   19,   18,   25,   20,   19,
       34,   26,   20,   15,   34,   14,   16,   17,   19,   18,
       16,   22,   25,   31,   31,   22,   23,   18,   16,   21,
       23,   16,   20,   21,   16,   21,   37,   16,   24,   21,
       37,   30,   24,   30,   35,   22,   21,   24,   38,   39,

       23,   35,   38,   39,   39,   40,   42,   37,   41,   40,
       42,   24,   41,   43,   45,   42,   38,   43,   45,   58,
       36,   32,   44,   40,   41,   41,   44,   29,   28,   46,
       47,   48,   41,   46,   47,   48,   43,   45,    9,   47,
       44,   49,   46,    8,   50,   49,   48,   48,   50,   51,
        3,    0,   52,   51,   50,   49,   52,   53,   54,   55,
       56,   53,   54,   55,   56,   52,   60,   61,    0,   62,
       60,   61,   61,   62,   53,   63,    0,    0,   64,   63,
       55,   54,   64,   65,   62,   66,   67,   65,   68,   66,
       67,   70,   68,   68,   71,   70,   63,   69,   71,   65,

       64,   69,   69,   67,    0,   72,    0,   71,   66,   72,
       70,   73,   74,   75,   76,   73,   74,   75,   76,   75,
       77,   78,    0,   76,   77,   78,   73,   74,   72,   79,
       80,   83,   81,   79,   80,   83,   81,   84,   85,   86,
        0,   84,   85,   86,   78,   81,   87,   85,    0,   88,
       87,    0,   79,   88,   90,   87,   89,    0,   90,    0,
       89,   86,   88,   84,   91,   89,   92,   93,   91,   94,
       92,   93,   92,   94,   95,   96,   97,   90,   95,   96,
       97,   98,   99,   96,  100,   98,   99,   91,  100,   99,
       98,  101,   94,  102,  104,  101,  105,  102,  104,  107,

      105,  106,    0,  107,  101,  106,  106,  108,  107,  109,
      102,  108,  110,  109,  111,  112,  110,  113,  111,  112,
        0,  113,  113,  114,  112,  115,    0,  114,    0,  115,
      116,  117,  109,    0,  116,  117,  114,  110,  121,  118,
      122,  119,  121,  118,  122,  119,  123,  115,    0,  114,
      123,  116,  119,    0,  117,  118,  124,  122,  125,  126,
      124,  127,  125,  126,  128,  127,  129,  130,  128,  123,
      129,  130,  131,  128,  132,  133,  131,    0,  132,  133,
        0,  125,  134,  127,  133,  136,  134,  137,  138,  136,
      139,  137,  138,  140,  139,  141,  142,  140,    0,  141,

      142,  144,  140,  145,  146,  144,  148,  145,  146,  150,
      148,  152,  154,  150,  156,  152,  154,  141,  156,  158,
      160,  162,  164,  158,  160,  162,  164,  166,  168,  170,
      172,  166,  168,  170,  172,  174,  176,  178,  180,  174,
      176,  178,  180,  182,  184,  186,  188,  182,  184,  186,
      188,  190,  192,  194,  196,  190,  192,  194,  196,  198,
      200,  202,  204,  198,  200,  202,  204,  206,  208,  210,
      212,  206,  208,  210,  212,  214,  216,  218,  220,  214,
      216,  218,  220,  222,  224,  226,  228,  222,  224,  226,
      228,  230,  232,  234,  236,  230,  232,  234,  236,  238,

      240,  242,  244,  238,  240,  242,  244,  246,  248,  250,
      252,  246,  248,  250,  252,  254,  256,  258,  260,  254,
      256,  258,  260,  262,  264,  266,  268,  262,  264,  266,
      268,  270,  272,  274,  276,  270,  272,  274,  276,  278,
      280,  282,  284,  278,  280,  282,  284,  286,  288,  290,
      292,  286,  288,  290,  292,  294,  296,  298,  300,  294,
      296,  298,  300,  302,  304,  306,  308,  302,  304,  306,
      308,  310,  312,  314,  316,  310,  312,  314,  316,  318,
      320,  322,  324,  318,  320,  322,  324,  326,  328,  330,
        0,  326,  328,  330,  335,  335,  335,  335,  336,    0,

      336,  336,  337,  337,  338,  338,  339,  339,  340,  340,
      341,  341,  342,  342,  343,  343,  344,  344,  345,  345,
      346,  346,  347,  347,  348,  348,  349,  349,  350,  350,
      351,  351,  352,  352,  353,  353,  354,  354,  355,  355,
      356,  356,  357,  357,  358,  358,  359,  359,  360,  360,
      361,  361,  362,  362,  363,  363,  364,  364,  365,  365,
      366,  366,  367,  367,  368,  368,  369,  369,  370,  370,
      371,  371,  372,  372,  373,  373,  374,  374,  375,  375,
      376,  376,  377,  377,  378,  378,  379,  379,  380,  380,
      381,  381,  382,  382,  383,  383,  384,  384,  385,  385,

      386,  386,  387,  387,  388,  388,  389,  389,  390,  390,
      391,  391,  392,  392,  393,  393,  394,  394,  395,  395,
      396,  396,  397,  397,  398,  398,  399,  399,  400,  400,
      401,  401,  402,  402,  403,  403,  404,  404,  405,  405,
      406,  406,  407,  407,  408,  408,  409,  409,  410,  410,
      411,  411,  412,  412,  413,  413,  414,  414,  415,  415,
      416,  416,  417,  417,  418,  418,  419,  419,  420,  420,
      421,  421,  422,  422,  423,  423,  424,  424,  425,  425,
      426,  426,  427,  427,  428,  428,  429,  429,  430,  430,
      431,  431,  432,  432,  433,  433,  434,  434,  435,  435,

      436,  436,  437,  437,  438,  438,  439,  439,  440,  440,
      441,  441,  442,  442,  443,  443,  444,  444,  445,  445,
      446,  446,  447,  447,  448,  448,  449,  449,  450,  450,
      451,  451,  452,  452,  453,  453,  454,  454,  455,  455,
      456,  456,  457,  457,  458,  458,  459,  459,  460,  460,
      461,  461,  462,  462,  463,  463,  464,  464,  465,  465,
      466,  466,  467,  467,  468,  468,  469,  469,  470,  470,
      471,  471,  472,  472,  473,  473,  474,  474,  475,  475,
      476,  476,  477,  477,  478,  478,  479,  479,  480,  480,
      481,  481,  482,  482,  483,  483,  484,  484,  485,  485,

      486,  486,  487,  487,  488,  488,  489,  489,  490,  490,
      491,  491,  492,  492,  493,  493,  494,  494,  495,  495,
      496,  496,  497,  497,  498,  498,  499,  499,  500,  500,
      501,  501,  502,  502,  503,  503,  504,  504,  505,  505,
      506,  506,  507,  507,  508,  508,  509,  509,  510,  510,
      511,  511,  512,  512,  513,  513,  514,  514,  515,  515,
      516,  516,  517,  517,  518,  518,  519,  519,  520,  520,
      521,  521,  522,  522,  523,  523,  524,  524,  525,  525,
      526,  526,  527,  527,  528,  528,  529,  529,  530,  530,
      531,  531,  532,  532,  533,  533,  534,  534,  535,  535,

      536,  536,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tool/miniscanner.l"
#define INITIAL 0
#line 2 "tool/miniscanner.l"
#include <stdio.h>
#include "miniscanner.h"
#line 747 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 6 "tool/miniscanner.l"

#line 900 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 335 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1003 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 7 "tool/miniscanner.l"
{ return KEYWORD_CREATE; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 8 "tool/miniscanner.l"
{ return KEYWORD_DATABASE; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 9 "tool/miniscanner.l"
{ return KEYWORD_DROP; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 10 "tool/miniscanner.l"
{ return KEYWORD_EXIT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 11 "tool/miniscanner.l"
{ return KEYWORD_QUIT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 12 "tool/miniscanner.l"
{ return KEYWORD_CLOSE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 13 "tool/miniscanner.l"
{ return KEYWORD_ENTITY; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 14 "tool/miniscanner.l"
{ return KEYWORD_ENTITIES; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 15 "tool/miniscanner.l"
{ return KEYWORD_COMMIT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 16 "tool/miniscanner.l"
{ return KEYWORD_CONTEXT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 17 "tool/miniscanner.l"
{ return KEYWORD_SET; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 18 "tool/miniscanner.l"
{ return KEYWORD_FIELD; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 19 "tool/miniscanner.l"
{ return KEYWORD_FIELDS; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 20 "tool/miniscanner.l"
{ return KEYWORD_STRING; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 21 "tool/miniscanner.l"
{ return KEYWORD_NUMBER; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 22 "tool/miniscanner.l"
{ return KEYWORD_OBJECT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 23 "tool/miniscanner.l"
{ return KEYWORD_ARRAY; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 24 "tool/miniscanner.l"
{ return KEYWORD_BOOLEAN; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 25 "tool/miniscanner.l"
{ return KEYWORD_NULL; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 26 "tool/miniscanner.l"
{ return KEYWORD_COUNT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 27 "tool/miniscanner.l"
{ return KEYWORD_UP; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 28 "tool/miniscanner.l"
{ return KEYWORD_RUNTIME; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 29 "tool/miniscanner.l"
{ return KEYWORD_ON; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 30 "tool/miniscanner.l"
{ return KEYWORD_OFF; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 31 "tool/miniscanner.l"
{ return KEYWORD_CHARSET; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 33 "tool/miniscanner.l"
{ return TOKEN_INTNUM; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 34 "tool/miniscanner.l"
{ return TOKEN_FLOATNUM; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 36 "tool/miniscanner.l"
{ return TOKEN_CHAR; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 37 "tool/miniscanner.l"
{ return(TOKEN_STRING); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 39 "tool/miniscanner.l"
{ return TOKEN_IDENTIFIER; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 40 "tool/miniscanner.l"
{ return TOKEN_LETTER; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 42 "tool/miniscanner.l"
{ return 0; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 43 "tool/miniscanner.l"
{ ; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 44 "tool/miniscanner.l"
{ ; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 45 "tool/miniscanner.l"
ECHO;
	YY_BREAK
#line 1158 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 335 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 335 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 334);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 45 "tool/miniscanner.l"


int yywrap()
{
    return 1;
}