#define KEYWORD_CREATE      1
#define KEYWORD_DATABASE    2
#define KEYWORD_DROP        3
#define KEYWORD_EXIT        4
#define KEYWORD_CLOSE       5
#define KEYWORD_ENTITY      6
#define KEYWORD_ENTITIES    7
#define KEYWORD_COMMIT      8
#define KEYWORD_CONTEXT     9
#define KEYWORD_SET         10
#define KEYWORD_FIELD       11
#define KEYWORD_FIELDS      12
#define KEYWORD_STRING      13
#define KEYWORD_NUMBER      14
#define KEYWORD_OBJECT      15
#define KEYWORD_ARRAY       16
#define KEYWORD_BOOLEAN     17
#define KEYWORD_NULL        18
#define KEYWORD_COUNT       19
#define KEYWORD_UP          20
#define KEYWORD_RUNTIME     21
#define KEYWORD_ON          22
#define KEYWORD_OFF         23
#define KEYWORD_CHARSET     24
#define KEYWORD_QUIT        25

#define TOKEN_STRING        100
#define TOKEN_IDENTIFIER    101
#define TOKEN_LETTER        102
#define TOKEN_CHAR          103
#define TOKEN_INTNUM        104
#define TOKEN_FLOATNUM      105
